
DROP TYPE NOLDOR_T;
DROP TYPE SILVAN_T;
DROP TYPE TELERI_T;
DROP TYPE SINDAR_T;
DROP TYPE ELF_T;
DROP TYPE MAN_T;
DROP TYPE HOBBIT_T;
DROP TYPE ORC_T;
DROP TYPE MAIA_T;
DROP TYPE GOBLIN_T;
DROP TYPE DWARF_T;
DROP TYPE BASE_T;
